In [1]:
# Importar numpy e utilizar um alias para poder utilizar os seus recursos
import numpy as np

# Criar um array de elementos (do 10 a 100)
array1 = np.arange(10, 101)

# Inverter o array
array1_invertido = array1[::-1]

# Criar um array 3x3 com valores de 0 a 8
array2 = np.arange(9).reshape(3, 3)

# Criar um array identidade de 6x6
array_identidade = np.eye(6)

# Criar um array com valores ao acaso com forma 3x3x3
array_aleatorio = np.random.random((3, 3, 3))

# Criar dois arrays, com valores ao acaso, A e B
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Verificar se os arrays A e B são iguais
sao_iguais = np.array_equal(A, B)

# Alternativamente, você pode verificar a igualdade elemento a elemento usando np.all
sao_iguais_elemento_a_elemento = np.all(A == B)

# Outra opção é verificar se os elementos estão aproximadamente próximos dentro de uma tolerância
sao_aproximadamente_iguais = np.allclose(A, B)

# Imprimir os resultados
print("Array de 10 a 100:", array1)
print("Array invertido:", array1_invertido)
print("Array 3x3 com valores de 0 a 8:")
print(array2)
print("Array identidade de 6x6:")
print(array_identidade)
print("Array aleatório 3x3x3:")
print(array_aleatorio)
print("Os arrays A e B são iguais:", sao_iguais)
print("Os arrays A e B são iguais elemento a elemento:", sao_iguais_elemento_a_elemento)
print("Os arrays A e B são aproximadamente iguais:", sao_aproximadamente_iguais)



Array de 10 a 100: [ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Array invertido: [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
Array 3x3 com valores de 0 a 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array identidade de 6x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Array alea

In [3]:
dollars = np.random.randint(1, 1001, 100)
conversion_rate = 0.874413
euros = dollars * conversion_rate
euros = np.round(euros, 2)
print(euros)


[256.2   66.46 434.58 866.54 732.76 407.48 369.88 550.88 427.59 128.54
 500.16 283.31 273.69 649.69 470.43 872.66  34.1   47.22 415.35 701.28
 481.8  865.67 387.36 170.51 174.88 605.97 487.05 431.96 509.78 331.4
  25.36 326.16  97.06 346.27 601.6   62.96 214.23 246.58 843.81 443.33
 856.05 319.16 334.03 417.97 619.08 378.62 456.44 461.69 146.9  365.5
 365.5  508.03 178.38 629.58 828.94  97.06 243.09 362.88  15.74 280.69
 597.22 602.47 860.42 696.91 274.57 874.41 446.83 348.89 494.04 222.1
 420.59 842.93 584.11 253.58 791.34 302.55 814.95 708.27 300.8  485.3
   9.62 403.1  539.51 543.88 424.09 651.44  13.12 672.42 721.39 644.44
 793.09 153.9  219.48 437.21 431.09 164.39 263.2  657.56 141.65 776.48]


In [ ]:
import pandas as pd

# Load 05_05_imdb_títulos.csv as pandas dataframe and show first 5 records
df_titulos = pd.read_csv("05_05_imdb_títulos.csv")
print(df_titulos.head(5))

# Load 05_05_imdb_elencos.csv as pandas dataframe and show first 5 records
df_elencos = pd.read_csv("05_05_imdb_elencos.csv")
print(df_elencos.head(5))

# Show number of records in titles dataframe
print("Number of records in titles dataframe:", len(df_titulos))

# Show number of records in cast dataframe
print("Number of records in cast dataframe:", len(df_elencos))

# Show 5 oldest titles
print("5 oldest titles:")
print(df_titulos.sort_values("year").head(5)["title"])

# Show films containing the word "Drácula" and count number of films
dracula_films = df_titulos[df_titulos["title"].str.contains("Drácula")]
print("Number of films containing the word 'Drácula':", len(dracula_films))

# Show 10 most common titles
print("10 most common titles:")
print(df_titulos["title"].value_counts().head(10))

# Show first film titled "Romeo and Juliet"
romeo_juliet = df_titulos[df_titulos["title"] == "Romeo and Juliet"]
print("First film titled 'Romeo and Juliet':")
print(romeo_juliet.sort_values("year").head(1)["year"])

# List all films containing the word "Exorcist", ordered from oldest to newest
exorcist_films = df_titulos[df_titulos["title"].str.contains("Exorcist")]
print("Films containing the word 'Exorcist':")
print(exorcist_films.sort_values("year"))

# Show number of films made in 1950
print("Number of films made in 1950:", len(df_titulos[df_titulos["year"] == 1950]))

# Show number of films made from 1950 to 1959 (inclusive)
print("Number of films made from 1950 to 1959:", len(df_titulos[(df_titulos["year"] >= 1950) & (df_titulos["year"] <= 1959)]))

# Show all roles in "The Godfather" trilogy, grouping by role and showing the number of times the role appeared
godfather_titles = df_titulos[df_titulos["title"].str.contains("The Godfather")]
godfather_cast = df_elencos[df_elencos["tconst"].isin(godfather_titles["tconst"])]
print("Roles in 'The Godfather' trilogy:")
print(godfather_cast["nconst"].value_counts())

# Show complete cast of "Drácula" (1958), sorted by "n" value
dracula_1958 = df_titulos[(df_titulos["title"] == "Drácula") & (df_titulos["year"] == 1958)]
dracula_cast = df_elencos[df_elencos["tconst"].isin(dracula_1958["tconst"])].sort_values("n")
print("Complete cast of 'Drácula' (1958):")
print(dracula_cast)

# Show number of roles played by "Bruce Wayne" (including "Young Bruce Wayne")
bruce_wayne = df_elencos[df_elencos["primaryName"].str.contains("Bruce Wayne")]
print("Number of roles played by 'Bruce Wayne':", len(bruce_wayne))

# Show number of roles played by "Robert de Niro"
robert_de_niro = df_elencos[df_elencos["primaryName"] == "Robert De Niro"]
print("Number of roles played by 'Robert de Niro':", len(robert_de_niro))

charlton_heston = df_elencos[(df_elencos["name"] == "Charlton Heston") & (df_elencos["n"] == 1) & (df_elencos["year"] // 10 == 196)]
print("Lead roles (n=1) for Charlton Heston in the 60's, sorted by year (descending):")
print(charlton_heston.sort_values("year", ascending=False))

# Show number of roles for actors in the 50's
roles_actors_50s = df_elencos[(df_elencos["type"] == "actor") & (df_elencos["year"] // 10 == 195)]
print("Number of roles for actors in the 50's:", len(roles_actors_50s))

# Show number of roles for actresses in the 50's
roles_actresses_50s = df_elencos[(df_elencos["type"] == "actress") & (df_elencos["year"] // 10 == 195)]
print("Number of roles for actresses in the 50's:", len(roles_actresses_50s))